lb:
  image: 'tutum/haproxy:latest'
  links:
    - web
  ports:
    - '80:80'
  restart: always
  roles:
    - global

web:
  image: 'gszathmari/sritest-frontend:latest'
  autodestroy: always
  restart: on-failure
  target_num_containers: 1
